CREATE DATABASE PasswordManagementSystem;

Create Table Company (
	CompanyId INT IDENTITY(1,1) PRIMARY KEY,
	CompanyName NVARCHAR(100) NOT NULL,
	Domain NVARCHAR(255) NOT NULL
);

CREATE TABLE "User" (
    UserId INT IDENTITY(1,1) PRIMARY KEY,
    CompanyId INT FOREIGN KEY REFERENCES Company(CompanyId),
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL
);

CREATE TABLE Log (
	LogId INT IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL,
	Action NVARCHAR(255) NOT NULL,
	FOREIGN KEY (UserId) REFERENCES "User"(UserId)
);

CREATE TABLE Role (
	RoleId INT IDENTITY(1,1) PRIMARY KEY,
	RoleName NVARCHAR(100) NOT NULL
);

CREATE TABLE UserRole (
	UserRoleId INT IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL,
	RoleId INT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES "User"(UserId),
	FOREIGN KEY (RoleId) REFERENCES Role(RoleId)
);

CREATE TABLE Password (
	PasswordId INT IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL,
	EncryptedPassword NVARCHAR(255) NOT NULL,
	PasswordName NVARCHAR(255) NOT NULL,
	FOREIGN KEY (UserId) REFERENCES "User"(UserId)
);

CREATE TABLE PasswordRole (
	PasswordRoler INT IDENTITY(1,1) PRIMARY KEY,
	PasswordId INT NOT NULL,
	RoleId INT NOT NULL,
	FOREIGN KEY (PasswordId) REFERENCES Password(PasswordId),
	FOREIGN KEY (RoleId) REFERENCES Role(RoleId)
);

CREATE TABLE Label (
	LabelId INT IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL,
	PasswordId INT NOT NULL,
	LabelText NVARCHAR(255) NOT NULL,
	FOREIGN KEY (UserId) REFERENCES "User"(UserId),
	FOREIGN KEY (PasswordId) REFERENCES Password(PasswordId)
);

SELECT Table_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG = 'PasswordManagementSystem';